<html>
    <head>
        <title></title>
        <meta charset="utf-8">
    </head>
    <body>
        
        <form method="POST" action="">
            
            <input type="text" name=""/>
            
            <br>
            
            <input type="radio" name="calc" value"soma">Soma
            <input type="radio" name="calc" value"subtracao">Subtração
            <input type="radio" name="calc" value"multiplicacao">Multiplicação
            <input type="radio" name="calc" value"divisao">Divisão
            
            <br>
            
            <input type="submit" value="Submit"/>
            
        </form>
        
        <?php
        
        ?>
        
    </body>
</html>