<html>
<head>
<title> Calculadora Básica</title>
</head>
<body>
<form method="post" action="calculadora2.php">
valor 1:
<input type="text" name="valor1" size="4"/>
<select name="tipo">
<option selected="selected">dividir</option>
<option selected="selected">multiplicar</option>
<option selected="selected">somar</option>
<option selected="selected">subtrair</option>
</selected>
valor 2:
<input type="text" name="valor2" size="4"/>
<input type="submit" name="resultado" value="calcular"/>
</form>
</body>